image: python:3.12

definitions:
  steps:
    - step: &build
        name: Build and package
        script:
          - apt-get update && apt-get install -y zip
          - pip install -t dependencies -r requirements.txt
          - (cd dependencies; zip ../code.zip -r .)
          - zip code.zip -u lambda_function.py
        artifacts:
          - code.zip
    - step: &deploy_dev
        deployment: dev
        name: Upload to S3 and update Lambda
        script:
          - apt-get update && apt-get install -y awscli
          - aws s3 cp code.zip s3://${ZIP_BUCKET}/${LAMBDA_NAME}.zip
          - pipe: atlassian/aws-lambda-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              FUNCTION_NAME: ${LAMBDA_NAME}
              COMMAND: 'update'
              ZIP_FILE: 'code.zip'
              S3_BUCKET: ${ZIP_BUCKET}
              S3_KEY: '${LAMBDA_NAME}.zip'

pipelines:
  branches:
    dev:
      - step: *build
      - step: *deploy_dev
